In [37]:
# import all of the csvs into separate dataframes

import pandas as pd

# import https://github.com/johngunerli/Hedge-Fund-Reports/blob/e6a0035bcea33ae517d520f2886fbc31229b81b9/master_list.csv csv 

hedgefunds = pd.read_csv('https://raw.githubusercontent.com/johngunerli/Hedge-Fund-Reports/master/master_list.csv?token=GHSAT0AAAAAAB6JE3RQLBTECSSC236P2ZO6ZBXANHQ', index_col=0)

hedgefunds

                     nameOfIssuer     titleOfClass      cusip      value
0                10X GENOMICS INC         CL A COM  88025U109     475323
1            1LIFE HEALTHCARE INC              COM  68269G107     331008
2                360 DIGITECH INC     AMERICAN DEP  88557W101   25306218
3                           3M CO              COM  88579Y101    3448420
4                     ABBOTT LABS              COM  002824100  243820644
..                            ...              ...        ...        ...
815      ZIONS BANCORPORATION N A              COM  989701107    2659605
816                    ZOETIS INC             CL A  98978V103    4055039
817  ZOOM VIDEO COMMUNICATIONS IN             CL A  98980L101     483799
818     ZOOMINFO TECHNOLOGIES INC     COMMON STOCK  98980F104    2805680
819        ZTO EXPRESS CAYMAN INC  SPONSORED ADS A  98980A105   36849464

[820 rows x 4 columns]

In [38]:
# get the cusip of the GlobalTitans

globaltitans = pd.read_csv('./OtherIndexes/GlobalTitans.csv')


# use Fidelity500 to get the cusip of the stocks for globaltitans

fidelity500 = pd.read_csv('./500s/topHoldingsFidelity500.csv')

# drop the emptys 
fidelity500 = fidelity500.dropna()



# set the columns as security_name, market_value, ticker, and cusip


fidelity500.columns = ['security_name', 'market_value', 'ticker', 'cusip']

fidelity500 = fidelity500[['ticker', 'cusip']]

fidelity500

    ticker      cusip
0     AAPL   37833100
1     MSFT  594918104
2     AMZN   23135106
3     NVDA  67066G104
4     TSLA  88160R101
..     ...        ...
535    DVA  23918K108
536    FOX  35137L204
537   LUMN  550241103
538   DISH  25470M109
542    NWS  65249B208

[479 rows x 2 columns]

In [39]:
# remove header, country, corporation, industry

globaltitans = globaltitans.drop(['Header','Country', 'Corporation', 'Industry'], axis=1)


# get the right side of the semicolon in Ticker

globaltitans['Ticker'] = globaltitans['Ticker'].str.split(':').str[1]


# strip the space in the ticker

globaltitans['Ticker'] = globaltitans['Ticker'].str.strip()

In [40]:
# convert fidelity500 to a lookup dictionary
lookup = dict(fidelity500.values)

lookup

{'AAPL': '37833100',
 'MSFT': '594918104',
 'AMZN': '23135106',
 'NVDA': '67066G104',
 'TSLA': '88160R101',
 'BRK.B': '84670702',
 'GOOGL': '02079K305',
 'GOOG': '02079K107',
 'XOM': '30231G102',
 'UNH': '91324P102',
 'JPM': '46625H100',
 'JNJ': '478160104',
 'META': '30303M102',
 'V': '92826C839',
 'PG': '742718109',
 'HD': '437076102',
 'MA': '57636Q104',
 'CVX': '166764100',
 'ABBV': '00287Y109',
 'MRK': '58933Y105',
 'LLY': '532457108',
 'AVGO': '11135F101',
 'BAC': '60505104',
 'PEP': '713448108',
 'KO': '191216100',
 'PFE': '717081103',
 'COST': '22160K105',
 'TMO': '883556102',
 'WMT': '931142103',
 'CSCO': '17275R102',
 'MCD': '580135101',
 'DIS': '254687106',
 'WFC': '949746101',
 'ABT': '2824100',
 'CRM': '79466L302',
 'VZ': '92343V104',
 'DHR': '235851102',
 'CMCSA': '20030N101',
 'TXN': '882508104',
 'PM': '718172109',
 'ADBE': '00724F101',
 'NKE': '654106103',
 'BMY': '110122108',
 'RTX': '7.55E+105',
 'NFLX': '64110L106',
 'NEE': '65339F101',
 'QCOM': '747525103',
 'T': '00206R102',
 'ORCL': '68389X105',
 'UPS': '911312106',
 'COP': '20825C104',
 'HON': '438516106',
 'LOW': '548661107',
 'UNP': '907818108',
 'MS': '617446448',
 'AMD': '7903107',
 'CAT': '149123101',
 'AMGN': '31162100',
 'GS': '38141G104',
 'SCHW': '808513105',
 'SBUX': '855244109',
 'IBM': '459200101',
 'DE': '244199105',
 'INTU': '461202103',
 'PLD': '74340W103',
 'SPGI': '78409V104',
 'BA': '97023105',
 'ELV': '36752103',
 'LMT': '539830109',
 'CVS': '126650100',
 'AXP': '25816109',
 'BLK': '09247X101',
 'INTC': '458140100',
 'GILD': '375558103',
 'AMAT': '38222105',
 'C': '172967424',
 'BKNG': '09857L108',
 'ADI': '32654105',
 'GE': '369604301',
 'AMT': '03027X100',
 'ADP': '53015103',
 'CI': '125523100',
 'MDLZ': '609207105',
 'TJX': '872540109',
 'SYK': '863667101',
 'NOW': '81762P102',
 'TMUS': '872590104',
 'PGR': '743315103',
 'PYPL': '70450Y103',
 'MO': '02209S103',
 'REGN': '75886F107',
 'ISRG': '46120E602',
 'MMC': '571748102',
 'ZTS': '98978V103',
 'TGT': '8.76E+110',
 'SLB': '806857108',
 'VRTX': '92532F100',
 'FISV': '337738108',
 'DUK': '26441C204',
 'SO': '842587107',
 'NOC': '666807102',
 'BSX': '101137107',
 'BDX': '75887109',
 'CME': '12572Q105',
 'EOG': '26875P101',
 'LRCX': '512807108',
 'ITW': '452308109',
 'USB': '902973304',
 'CSX': '126408103',
 'PNC': '693475105',
 'EQIX': '29444U700',
 'APD': '9158106',
 'MU': '595112103',
 'HUM': '444859102',
 'TFC': '89832Q109',
 'CL': '194162103',
 'MMM': '88579Y101',
 'FCX': '35671D857',
 'MPC': '56585A102',
 'ICE': '45866F104',
 'CCI': '22822V101',
 'EL': '518439104',
 'WM': '94106L109',
 'SNPS': '871607107',
 'GM': '37045V100',
 'ATVI': '00507V109',
 'KLAC': '482480100',
 'CDNS': '127387108',
 'SHW': '824348106',
 'NSC': '655844108',
 'ORLY': '67103H107',
 'HCA': '40412C101',
 'GD': '369550108',
 'VLO': '91913Y100',
 'EW': '2.82E+112',
 'MCK': '58155Q103',
 'EMR': '291011104',
 'DG': '256677105',
 'FDX': '31428X106',
 'PSX': '718546104',
 'F': '345370860',
 'PXD': '723787107',
 'MET': '59156R108',
 'PSA': '74460D109',
 'AZO': '53332102',
 'GIS': '370334104',
 'SRE': '816851109',
 'D': '25746U109',
 'APH': '32095101',
 'MRNA': '60770K107',
 'MCO': '615369105',
 'ROP': '776696106',
 'MAR': '571903202',
 'AIG': '26874784',
 'AEP': '25537101',
 'PH': '701094104',
 'MCHP': '595017104',
 'CTVA': '22052L104',
 'MSI': '620076307',
 'ADM': '39483102',
 'TRV': '8.94E+113',
 'NUE': '670346105',
 'ADSK': '52769106',
 'DXCM': '252131107',
 'OXY': '674599105',
 'KMB': '494368103',
 'A': '00846U101',
 'MSCI': '55354G100',
 'COF': '14040H105',
 'CMG': '169656105',
 'DOW': '260557103',
 'LHX': '502431109',
 'EXC': '30161N101',
 'O': '756109104',
 'SPG': '828806109',
 'AJG': '363576109',
 'ECL': '278865100',
 'CHTR': '16119P108',
 'IDXX': '45168D104',
 'HLT': '43300A203',
 'BIIB': '09062X103',
 'MNST': '61174X109',
 'CNC': '15135B101',
 'IQV': '46266C105',
 'AFL': '1055102',
 'FTNT': '3.50E+113',
 'TDG': '893641100',
 'ROST': '778296103',
 'CTAS': '172908105',
 'SYY': '871829107',
 'PCAR': '693718108',
 'CARR': '14448C104',
 'FIS': '31620M106',
 'BK': '64058100',
 'HES': '42809H107',
 'PRU': '744320102',
 'WMB': '969457100',
 'AMP': '03076C106',
 'STZ': '21036P108',
 'DD': '26614N102',
 'YUM': '988498101',
 'PAYX': '704326107',
 'XEL': '98389B100',
 'OTIS': '68902V107',
 'DVN': '25179M103',
 'HSY': '427866108',
 'WELL': '95040Q104',
 'NEM': '651639106',
 'WBD': '934423104',
 'ANET': '40413106',
 'CMI': '231021106',
 'ALL': '20002101',
 'ROK': '773903109',
 'KMI': '49456B101',
 'ON': '682189105',
 'HAL': '406216101',
 'STT': '857477103',
 'AME': '31100100',
 'URI': '911363109',
 'VICI': '925652109',
 'CTSH': '192446102',
 'MTD': '592688105',
 'ED': '209115104',
 'ILMN': '452327109',
 'RMD': '761152107',
 'PPG': '693506107',
 'KHC': '500754106',
 'ODFL': '679580100',
 'BKR': '05722G100',
 'DFS': '254709108',
 'DLTR': '256746108',
 'GPN': '37940X102',
 'CPRT': '217204106',
 'PEG': '744573106',
 'GWW': '384802104',
 'DLR': '253868103',
 'ALB': '12653101',
 'FAST': '311900104',
 'KDP': '49271V100',
 'OKE': '682680103',
 'EA': '285512109',
 'DHI': '23331A109',
 'CSGP': '22160N109',
 'ENPH': '29355A107',
 'KEYS': '49338L103',
 'KR': '501044101',
 'SBAC': '78410G104',
 'WEC': '92939U106',
 'GEHC': '36266G107',
 'CDW': '12514G108',
 'CBRE': '12504L109',
 'MTB': '55261F104',
 'VRSK': '92345Y106',
 'ULTA': '90384S303',
 'RSG': '760759100',
 'ANSS': '03662Q105',
 'ES': '30040W108',
 'HPQ': '40434L105',
 'ZBH': '98956P102',
 'IT': '366651107',
 'GLW': '219350105',
 'TSCO': '892356106',
 'AWK': '30420103',
 'WBA': '931427108',
 'EIX': '281020107',
 'ABC': '3.07E+108',
 'PCG': '69331C108',
 'TROW': '74144T108',
 'GPC': '372460105',
 'FITB': '316773100',
 'EBAY': '278642103',
 'HIG': '416515104',
 'EFX': '294429105',
 'FANG': '25278X109',
 'LEN': '526057104',
 'DAL': '247361702',
 'CEG': '21037T109',
 'AVB': '53484101',
 'VMC': '929160109',
 'IFF': '459506101',
 'FTV': '34959J108',
 'IR': '45687V106',
 'WST': '955306105',
 'PWR': '7.48E+106',
 'WY': '962166104',
 'FRC': '33616C100',
 'ALGN': '16255101',
 'ARE': '15271109',
 'MLM': '573284106',
 'HBAN': '446150104',
 'EXR': '30225T102',
 'RF': '7591EP100',
 'MPWR': '609839105',
 'FE': '337932107',
 'AEE': '23608102',
 'EQR': '29476L107',
 'DTE': '233331107',
 'LH': '50540R409',
 'DOV': '260003108',
 'STLD': '858119100',
 'RJF': '754730109',
 'ETR': '29364G103',
 'CFG': '174610105',
 'CHD': '171340102',
 'PFG': '74251V102',
 'TDY': '879360105',
 'BAX': '71813109',
 'HPE': '42824C109',
 'LUV': '844741108',
 'PPL': '69351T106',
 'HOLX': '436440101',
 'NTRS': '665859104',
 'CAH': '14149Y108',
 'CTRA': '127097103',
 'VTR': '92276F100',
 'CLX': '189054109',
 'NDAQ': '631103108',
 'WAB': '929740108',
 'CINF': '172062101',
 'LVS': '517834107',
 'MKC': '579780206',
 'XYL': '98419M100',
 'MAA': '59522J103',
 'WAT': '941848103',
 'OMC': '681919106',
 'INVH': '46187W107',
 'VRSN': '9.23E+106',
 'MOS': '61945C103',
 'SWKS': '83088M102',
 'SEDG': '83417M104',
 'EPAM': '29414B104',
 'BALL': '58498106',
 'CNP': '15189T107',
 'DRI': '237194105',
 'CAG': '205887102',
 'TTWO': '874054109',
 'TSN': '902494103',
 'CMS': '125896100',
 'KEY': '493267108',
 'SIVB': '78486Q101',
 'UAL': '910047109',
 'IEX': '45167R104',
 'K': '487836108',
 'CF': '125269100',
 'TRGP': '87612G101',
 'FSLR': '336433107',
 'BBY': '86516101',
 'EXPD': '302130109',
 'BR': '11133T103',
 'AES': '00130H105',
 'EXPE': '30212P303',
 'FMC': '302491303',
 'COO': '216648402',
 'SYF': '87165B103',
 'MOH': '60855R100',
 'MRO': '565849106',
 'FLT': '339041105',
 'FDS': '303075105',
 'ATO': '49560105',
 'SJM': '832696405',
 'DGX': '74834L100',
 'TER': '880770102',
 'PKI': '714046109',
 'NVR': '62944T105',
 'HWM': '443201108',
 'ZBRA': '989207105',
 'IRM': '46284V101',
 'ETSY': '29786A106',
 'J': '46982L108',
 'TXT': '883203101',
 'JBHT': '445658107',
 'ESS': '297178105',
 'AVY': '53611109',
 'LKQ': '501889208',
 'LW': '513272104',
 'INCY': '45337C102',
 'PAYC': '70432V102',
 'NTAP': '64110D104',
 'POOL': '73278L105',
 'VTRS': '92556V106',
 'IPG': '460690100',
 'MGM': '552953101',
 'WRB': '84423102',
 'EVRG': '30034W106',
 'CBOE': '12503M108',
 'TYL': '902252105',
 'LDOS': '525327102',
 'PTC': '69370C100',
 'SNA': '833034101',
 'BRO': '115236101',
 'UDR': '902653104',
 'IP': '460146103',
 'PEAK': '42250P103',
 'LNT': '18802108',
 'MKTX': '57060D108',
 'HRL': '440452100',
 'TRMB': '896239100',
 'KIM': '49446R109',
 'SWK': '854502101',
 'PKG': '695156109',
 'PHM': '745867101',
 'APA': '03743Q108',
 'CTLT': '148806102',
 'CPT': '133131102',
 'WDC': '958102105',
 'EQT': '26884L109',
 'L': '540424108',
 'HST': '44107P104',
 'JKHY': '426281101',
 'BF.B': '115637209',
 'MAS': '574599106',
 'NDSN': '655663102',
 'BWA': '99724106',
 'CHRW': '12541W209',
 'CE': '150870103',
 'MTCH': '57667L107',
 'AKAM': '00971T101',
 'TECH': '09073M104',
 'GEN': '668771108',
 'CDAY': '15677J108',
 'WYNN': '983134107',
 'TFX': '879369106',
 'CRL': '159864107',
 'NI': '65473P105',
 'GL': '3.80E+106',
 'KMX': '143130102',
 'CZR': '12769G100',
 'PARA': '92556H206',
 'CCL': '143658300',
 'HSIC': '806407102',
 'FOXA': '35137L105',
 'CPB': '134429109',
 'TPR': '876030107',
 'DPZ': '25754A201',
 'AAL': '02376R102',
 'LYV': '538034109',
 'BIO': '90572207',
 'QRVO': '74736K101',
 'EMN': '277432100',
 'TAP': '60871R209',
 'JNPR': '48203R104',
 'REG': '758849103',
 'BXP': '101121101',
 'BBWI': '70830104',
 'CMA': '200340107',
 'RHI': '770323103',
 'AAP': '00751Y106',
 'HII': '446413106',
 'UHS': '913903100',
 'FFIV': '315616102',
 'BEN': '354613101',
 'PNW': '723484101',
 'AOS': '831865209',
 'VFC': '918204108',
 'XRAY': '24906P109',
 'ROL': '775711104',
 'WRK': '96145D105',
 'FRT': '313745101',
 'GNRC': '368736104',
 'ZION': '989701107',
 'NRG': '629377508',
 'WHR': '963320106',
 'SBNY': '82669G104',
 'HAS': '418056107',
 'SEE': '81211K100',
 'AIZ': '04621X108',
 'NWSA': '65249B109',
 'DXC': '23355L106',
 'OGN': '68622V106',
 'ALK': '11659109',
 'NWL': '651229106',
 'MHK': '608190104',
 'LNC': '534187109',
 'RL': '751212101',
 'DVA': '23918K108',
 'FOX': '35137L204',
 'LUMN': '550241103',
 'DISH': '25470M109',
 'NWS': '65249B208'}

In [41]:
# for all values in globaltitans, if the ticker is in fidelity500, then get the cusip

globaltitans['cusip'] = globaltitans['Ticker'].apply(lambda x: lookup[x] if x in lookup else None)

globaltitans

   Ticker      cusip
0     MMM  88579Y101
1    ABBV  00287Y109
2     ALV       None
3   GOOGL  02079K305
4    AMZN   23135106
5    AMGN   31162100
6     ABI       None
7    AAPL   37833100
8     BHP       None
9      BA   97023105
10     BP       None
11   BATS       None
12    CVX  166764100
13   CSCO  17275R102
14      C  172967424
15     KO  191216100
16     DD  26614N102
17    XOM  30231G102
18     FB       None
19     GE  369604301
20    GSK       None
21   HSBA       None
22   INTC  458140100
23    IBM  459200101
24    JNJ  478160104
25    JPM  46625H100
26     MA  57636Q104
27    MCD  580135101
28    MRK  58933Y105
29   MSFT  594918104
30   NESN       None
31   NOVN       None
32   NVDA  67066G104
33   ORCL  68389X105
34    PEP  713448108
35    PFE  717081103
36     PM  718172109
37     PG  742718109
38    ROG       None
39     RY       None
40   RDSA       None
41   SMSN       None
42    SAN       None
43    SIE       None
44    TSM       None
45    TOT       None
46      V  92826C839
47   7203       None
48    WMT  931142103
49    DIS  254687106

In [42]:
# if the cusip does not exist, it's most likely not an american company, so drop it

globaltitans = globaltitans.dropna()

globaltitans

   Ticker      cusip
0     MMM  88579Y101
1    ABBV  00287Y109
3   GOOGL  02079K305
4    AMZN   23135106
5    AMGN   31162100
7    AAPL   37833100
9      BA   97023105
12    CVX  166764100
13   CSCO  17275R102
14      C  172967424
15     KO  191216100
16     DD  26614N102
17    XOM  30231G102
19     GE  369604301
22   INTC  458140100
23    IBM  459200101
24    JNJ  478160104
25    JPM  46625H100
26     MA  57636Q104
27    MCD  580135101
28    MRK  58933Y105
29   MSFT  594918104
32   NVDA  67066G104
33   ORCL  68389X105
34    PEP  713448108
35    PFE  717081103
36     PM  718172109
37     PG  742718109
46      V  92826C839
48    WMT  931142103
49    DIS  254687106

In [43]:
# now use the hedgefunds dataframe's cusips and the globaltitans dataframe's cusips to get the common ones

hedgefund_cusips = hedgefunds['cusip'].tolist()

globaltitans_cusips = globaltitans['cusip'].tolist()


# get the common cusips

common_cusips = list(set(hedgefund_cusips) & set(globaltitans_cusips))

common_cusips

['30231G102',
 '594918104',
 '57636Q104',
 '166764100',
 '92826C839',
 '718172109',
 '478160104',
 '580135101',
 '713448108',
 '68389X105',
 '459200101',
 '17275R102',
 '58933Y105',
 '172967424',
 '742718109',
 '00287Y109',
 '46625H100',
 '02079K305',
 '191216100',
 '717081103',
 '88579Y101',
 '369604301',
 '931142103']

In [44]:
# then, find what these common cusips are in the hedgefunds dataframe

strategic_funds = hedgefunds[hedgefunds['cusip'].isin(common_cusips)]

# reset index and show the dataframe

strategic_funds = strategic_funds.reset_index(drop=True)

strategic_funds

strategic_funds.to_csv('strategic_funds.csv')

# convert this to excel 

strategic_funds.to_excel('strategic_funds.xlsx')